// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwvdlmgpgyfpzoyrduok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3dmRsbWdwZ3lmcHpveXJkdW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODgzNzUsImV4cCI6MjA3MzI2NDM3NX0.3AcQxWYmfd-zFpBpIrhB1wrbfPvkGGhsmH882NenVX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});